######################################################################
# Automatically generated by qmake (2.01a) Sun Apr 28 11:19:18 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /ad/eng/users/i/c/icb/Desktop/EC535/project/newqt/. .

# Input
HEADERS += Rfid.h
SOURCES += main.cpp Rfid.cpp
